name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: hello world
      id: hello-world
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: hello world
        setup-command: dotnet tool install -g dotnet-script
        command: dotnet script helloworld.cs
        timeout: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HELLO-WORLD_RESULTS: "${{steps.hello-world.outputs.result}}"
      with:
        runners: hello-world
